# Dockerfile.python
FROM python:3.9

WORKDIR /app

USER root
# Install system dependencies if needed
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libev4 \
    libev-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements files
COPY requirements.sink-source.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.sink-source.txt