FROM bitnami/spark:3.5.2

USER root
# Ensure apt list directory exists, then update and install pip
RUN apt-get update && apt-get install python3-pip -y

# Copy requirements.txt and install Python dependencies
COPY requirements.txt /app/
RUN pip3 install -r /app/requirements.txt
